name: Sync to Friend's Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add friend's repository as a remote
      run: git remote add friend https://crashkat:${{ secrets.FRIEND_REPO_PAT }}@github.com/crashkat/gh_repo_synch_test

    - name: Push changes to friend's repository
      run: |
        git fetch friend
        echo "fetch friend complete"
        git checkout -b integration
        echo "checkout integration branch complete"
        git merge main
        echo "merge to main complete"
        git push friend integration
        echo "push remote integration branch complete"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.FRIEND_REPO_PAT }}
        commit-message: Sync from my main branch
        branch: integration
        base: main
        title: 'Sync from my main branch'
        body: 'This PR syncs changes from my main branch to your main branch.'
