on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

name: on-commit-to-main

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_REPO_PAT }}

      - name: Clone friend's repository
        run: |
          REPOSITORY="crashkat/gh_repo_synch_test"
          FOLDER="bin/$REPOSITORY"
          git clone --depth=1 --branch=main https://crashkat:${{ secrets.FRIEND_REPO_PAT }}@github.com/$REPOSITORY $FOLDER

      - name: Compare scripts folders
        run: |
          diff -r scripts $FOLDER/scripts || echo "Differences found"

      - name: Create pull request if differences found
        if: success() # This step will only run if the previous step found differences
        run: |
          LATEST_TAG=$(git describe --tags --always --abbrev=0)
          BRANCH_NAME="chore-update-scripts-to-$LATEST_TAG"

          cd $FOLDER
          git config user.email "maacah@live.com"
          git config user.name "maacah"
          git checkout -b $BRANCH_NAME
          cp -R ../../../scripts scripts
          git add .
          git commit -m "chore: update scripts to $LATEST_TAG"
          git push origin $BRANCH_NAME

          echo "${{ secrets.FRIEND_REPO_PAT }}" > token.txt
          gh auth login --with-token < token.txt
          gh pr create --body "" --title "chore: update scripts to $LATEST_TAG" --head "$BRANCH_NAME" --base "main"

